### PR TITLE
♻️Run npm audit instead of nsp

### PR DESCRIPTION
**Pull request by charlyx**
👋Hello,

First of all, thanks for your work 👍

Unfortunately, NSP has been deprecated by the author: https://www.npmjs.com/package/nsp
We should now be using `npm audit`: https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

This pull request will help us install our project again 😅

> error /node_modules/@echo-health/koa-prometheus-exporter: Command failed.
> Exit code: 2
> Command: nsp check
> Arguments: 
> Directory: /node_modules/@echo-health/koa-prometheus-exporter
> Output:
> (+) Client request error: getaddrinfo ENOTFOUND api.nodesecurity.io api.nodesecurity.io:443

### CODE REVIEW

**Comment by paul-leathwood** [comment]
Good Stuff, we've just come across this problem too. Glad to see a PR already in place

**Comment by charlyx** [comment]
Hey folks,

Since I need this package to be fixed and I don't want to just copy/paste the code into my codebase,
I decided to publish my fork... Actually, I just did.

Here it is: https://www.npmjs.com/package/koa-prometheus-exporter

@echo-health people, I'm happy to remove my fork as soon as your package gets fixed. Thanks again, for your work.

**Comment by ghost** [comment]
Seems to be already fixed in [1.0.3](https://github.com/echo-health/koa-prometheus-exporter/tree/1.0.3), but not announced here.

**Comment by zoltrain** [comment]
Hi All,

@charlyx firstly thanks for the contribution, sorry for the very late reply. We've been a bit blind sided by work and this has fallen through the cracks. As @Yuket pointed out we fixed this by requiring a newer version of the node runtime (this is 8 or above, I think current LTS is 10, so not supporting lower than 8 seems reasonable?). One where `npm audit` is run by default.

I've just applied a bunch of security updates to the runtime and dev dependencies in master and published a new version to npm for those that want to upgrade.

@charlyx I see you've done some doc editing which would be great to integrate back into master. If you can remove the postinstall hook then I can merge these in (otherwise it will run `npm audit` twice)

Once again sorry all for the late reply.

**Pull request closed without merging**
